api/urls.py
from django.urls import path
from . import views


app_name = "api"
urlpatterns = [
    path("add_song", views.add_song, name="add_song"),
    path("get_audio/<int:id>", views.get_audio, name="get_audio"),
    path("save_volume", views.save_volume, name="save_volume"),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static   
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("users.urls", namespace="users")),
    path("", include("api.urls", namespace="api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

users/urls.py
from django.urls import path
from . import views


app_name = "users"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile")
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

from main.models import History, Song, Statistic


# Create your models here.
class User(AbstractUser):
    image = models.ImageField(upload_to="users_img", blank=True, null=True, verbose_name="Аватар")
    email = models.EmailField(unique=True, blank=True, null=True)
    songs = models.ManyToManyField(Song)
    listened_songs = models.ManyToManyField(Song, through=History, related_name="listened_songs")
    statistic = models.OneToOneField(Statistic, on_delete=models.CASCADE, related_name='user_stat', null=True, blank=True)
    
    class Meta:
        db_table = "users"
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username
    

@receiver(post_save, sender=User)
def create_stat(sender, instance, created, **kwargs):
    if created:
        stat = Statistic.objects.create()
        instance.statistic = stat
        instance.save()

users/forms.py
import email
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django import forms

from .models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Имя пользователя")
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ["username", "password"]


class RegistrationUserForm(UserCreationForm):
    username = forms.CharField(label="Имя пользователя")
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput())
    password2 = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")
        labels = {
            "email": "Почтовый ящик",
            "first_name": "Имя",
            "last_name": "Фамилия",
        }

    # def clean_email(self):
    #     email = self.cleaned_data["email"]
    #     if get_user_model().objects.filter(email=email).exists():
    #          raise forms.ValidationError("This Email already exists!")
    #     return email
    

class ProfileForm(UserChangeForm):
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "image"]

users/views.py
from hashlib import file_digest
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import LoginForm, RegistrationUserForm, ProfileForm


# Create your views here.
def login(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(request, username=username, password=password)
            if user:
                auth.login(request, user)
                if request.POST.get("next", None):
                    return redirect(request.POST.get("next", None))

                return redirect("main:home")
    else:
        form = LoginForm()
        
    return render(request, "users/login.html", {"title": "Log in", "form": form,})

def registration(request):
    if request.method == "POST":
        form = RegistrationUserForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return redirect("main:home")
    else:
        form = RegistrationUserForm()

    context = {
        "title": "Registration",
        "form": form,
    }
    return render(request, "users/registration.html", context)

@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse("main:home"))

@login_required
def profile(request):
    if request.method == "POST":
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES) # files=request.FILES
        if form.is_valid():
            form.save()
            return redirect("users:profile")
    else:
        form = ProfileForm(instance=request.user)

    context = {
        "title": "Profile",
        "form": form,
    }
    return render(request, "users/profile.html", context)

users/templates/users/base_users.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "styles/style.css" %}">
    <link rel="stylesheet" href="{% static "style_users.css" %}">
    <title>{{ title }}</title>
</head>
<body class="body">
    {% block main %}
    {% endblock main %}
</body>
</html> 

users/templates/users/login.html
{% extends "users/base_users.html" %}
{% load static %}


{% block main %}
<main>
    <form  action="{% url "users:login" %}" method="post" class="flexform">
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        {{ form }}
        <div class="form_button">
            <button type="submit" class="button">Войти</button>
        </div>
    </form>
</main>
{% endblock main %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<form action="{% url "users:profile" %}" method="POST" class="flexform" enctype="multipart/form-data"> 
    {% csrf_token %}
    <div class="field">
        {% if user.image %}
            <img src="{{ user.image.url }}" alt="Profile image" class="profile_img">
        {% else %}
            <img src="{% static "images/avatar.jpg" %}" alt="Profile image" class="profile_img">
        {% endif %}
        <input type="file" name="image" id="image">
        
        {% if form.image.errors %}
            <div>{{ form.image.errors }}</div>
        {% endif %}
    </div>
    <div class="field">
        <label for="id_first_name">Имя</label>
        <input type="text" id="id_first_name" name="first_name" value="{{ form.first_name.value }}" required>
        {% if form.first_name.errors %}
            <div>{{ form.first_name.errors }}</div>
        {% endif %}
    </div>
    <div class="field">
        <label for="id_last_name">Фамилия</label>
        <input type="text" id="id_first_name" name="last_name" value="{{ form.last_name.value }}" required>
        {% if form.last_name.errors %}
            <div>{{ form.last_name.errors }}</div>
        {% endif %}
    </div>
    <div class="field">
        <label for="id_username">Имя пользователя</label>
        <input type="text" id="id_first_name" name="username" value="{{ form.username.value }}" required>
        {% if form.username.errors %}
            <div>{{ form.username.errors }}</div>
        {% endif %}
    </div>
    <div class="field">
        <label for="id_email">Почтовый ящик</label>
        <input type="text" id="id_email" name="email" value="{{ form.email.value }}" required>
        {% if form.email.errors %}
            <div>{{ form.email.errors }}</div>
        {% endif %}
    </div>
    <div class="form_button">
        <button type="submit" class="button">Изменить</button>
    </div>
</form>
{% endblock content %}

users/templates/users/registration.html
{% extends "users/base_users.html" %}
{% load static %}

{% block main %}
<main>
    <form action="{% url "users:registration" %}" method="post">
        {% csrf_token %}
        {{ form }}
        <div class="form_button">
            <button type="submit" class="button">Отправить</button>
        </div>
    </form>
</main>
{% endblock main %}