api/urls.py
from django.urls import path
from . import views


app_name = "api"
urlpatterns = [
    path("add_song", views.add_song, name="add_song"),
    path("get_audio/<int:id>", views.get_audio, name="get_audio"),
    path("save_volume", views.save_volume, name="save_volume"),
]

main/urls.py
from django.urls import path
from main import views


app_name = "main"
urlpatterns = [
    path("", views.home, name="home"),
    path("statistics/", views.statistics, name="statistics"),
    path("support/", views.support, name="support"),
    path("favourites/", views.favourites, name="favourites"),
    path("history/", views.history, name="history"),
    path("search", views.search, name="search")
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static   
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("users.urls", namespace="users")),
    path("", include("api.urls", namespace="api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

main/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Song(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    artist = models.CharField(max_length=100, verbose_name="Исполнитель")
    image = models.ImageField(upload_to="songs_img", verbose_name="Изображение")
    audio = models.FileField(upload_to="songs", verbose_name="Аудио")
    count = models.IntegerField(default=0)

    class Meta:
        db_table = "song"
        verbose_name = "Песня"
        verbose_name_plural = "Песни"

    def __str__(self):
        return f"{self.artist}: {self.name}"    


class Support(models.Model):
    username = models.CharField(max_length=150, verbose_name="Имя пользователя")
    email = models.EmailField()
    text = models.TextField()
    time_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "support"
        ordering = ["-time_created"]


class History(models.Model):
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_listened = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'history'


class Statistic(models.Model):
    added_to_favourites = models.IntegerField(default=0, verbose_name='Добавлено')

    class Meta:
        db_table = 'statistic'

main/forms.py
from django import forms

from .models import Support


class SupportForm(forms.ModelForm):
    template_name = "form_snippet.html"
    
    class Meta:
        model = Support
        fields =  ("username", "email", "text")

main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required 
from django.core.paginator import Paginator
from django.contrib.postgres.search import SearchVector

from .forms import SupportForm
from .models import Song
from users.models import User


# Create your views here.
def home(request):
    songs = Song.objects.order_by("-id")

    context = {
        "title": "Home",
        "songs": songs,
    }
    return render(request, "main/home.html", context)

@login_required
def statistics(request):
    return render(request, "main/statistics.html", {"statistic": request.user.statistic})

@login_required
def support(request):
    if request.method == "POST":
        form = SupportForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = SupportForm()

    context = {
        "title": "Support",
        "form": form,
    }

    return render(request, "main/support.html", context)

@login_required
def favourites(request):
    user = User.objects.get(pk=request.user.id)
    if user:
        user_songs = user.songs.all()
    return render(request, "main/favourites.html", {"title": "Favourites", "user_songs": user_songs})

@login_required
def history(request):
    number = request.GET.get("page", 1)

    history = request.user.listened_songs.order_by("-history__date_listened")
    paginator = Paginator(history, 5)

    songs = paginator.page(number)
    return render(request, "main/history.html", {"songs": songs})

def search(request):
    query = request.POST.get("search", None)
    
    if query:
        songs = Song.objects.annotate(search=SearchVector("name", "artist"),).filter(search=query)
    else:
        songs = []

    context = {
        "title": "Home",
        "songs": songs,
    }
    return render(request, "main/home.html", context)

main/templates/main/favourites.html
{% extends "base.html" %}
{% load static %}
{% load main_tags %}

{% block content %}
<h2>Избранное</h2>
{% for song in user_songs %}
    {% show_song song %}
{% endfor %}
{% endblock content %}

{% block aside %}
{% endblock aside %}

{% block scripts%}
<script>
{% if request.session.fav_song_id%}
    getAudio({{ request.session.fav_song_id }}, auto_play=false, addtohistory=false)
{% endif %}
</script>
{% endblock %}

main/templates/main/history.html
{% extends "base.html" %}
{% load static %}
{% load main_tags %}


{% block content %}
<h2>История</h2>
{% for song in songs %}
    {% show_song song %}
{% endfor %}

<div class="pagination">
    <ul>
        <a {% if songs.has_previous %}href="?page={{ songs.previous_page_number }}"{% else %}disabled{% endif %}>
            <li >Prev</li>
        </a>

        {% for page in songs.paginator.page_range %}
            {% if page >= songs.number|add:-2 and page <= songs.number|add:2 %}
                <a href="?page={{ page }}" {% if page == songs.number %}style="background-color: #D38162"{% endif %}>
                    <li>{{ page }}</li>
                </a>
            {% endif %}
        {% endfor %}

        <a {% if songs.has_next %}href="?page={{ songs.next_page_number }}"{% else %}disabled{% endif %}>
            <li>Next</li>
        </a>
    </ul>
</div>
</div>

{% endblock content%}

{% block player %}
<h3>Плеер недоступен в истории</p>
{% endblock %}

{% block scripts %}
<script>
{% if request.session.history_song_id %}
    getAudio({{ request.session.history_id }}, auto_play=false, addtohistory=false)
{% endif %}
</script>
{% endblock %}

main/templates/main/home.html
{% extends "base.html" %}
{% load static %}
{% load main_tags %}

{% block content %}
<h2>Главная</h2>
<div class="main_content">
    <ul class="main_nav">
        <li>Песни</li>
        <li>Альбомы</li>
        <li>Артисты</li>
    </ul>
    {% for song in songs %}
        {% show_song song %}
    {% endfor %}
{% endblock content %}

main/templates/main/statistics.html
{% extends "base.html" %}

{% block content %}

<h1>Статистика</h1>
<section class="stat">
    <div class="stat_info">
        <span>Added to favorites </span>
        <p>{{ statistic.added_to_favourites }} songs</p>
    </div>
    <div class="stat_info">
        <span>Account creation time</span>
        <p>{{ request.user.date_joined|date:"G:i:s j-m-Y" }}</p>
    </div>
</section>
{% endblock content %}

main/templates/main/support.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Поддержка</h1>
<form action={% url "main:support" %} method="post" class="flexform">
    {% csrf_token %}
    {{ form }}
    <div class="form_button">
        <button type="submit" class="button">Send</button>
    <div>
</form>
{% endblock content %}